import { lessonSchema, exerciseSchema, type Lesson, type Exercise } from "../src/content/types";

const quality={method:"ai-authored-and-reviewed",reviewedAt:"2026-09-23",unresolved:[]} as const;
type Input = Omit<Exercise,"normalize"|"transfer"|"exit"> & Partial<Pick<Exercise,"normalize"|"transfer"|"exit">>;
const ex=(input:Input)=>exerciseSchema.parse(input);
const choice=(id:string,prompt:string,options:string[],answer:string,explanation:string,skill:string,tag:string,exit=false)=>ex({id,type:"choice",prompt,options,accepted:[answer],explanation,hint:"Identify the meaning and grammatical role before choosing the form.",skill,family:id.split("-Q")[0]+"-recognition",errorTag:tag,exit});
const short=(id:string,prompt:string,answers:string[],explanation:string,skill:string,tag:string,exit=false)=>ex({id,type:"short",prompt,accepted:answers,explanation,hint:"Use the lesson's decision steps. Write only the requested words.",skill,family:id.split("-Q")[0]+"-production",errorTag:tag,transfer:true,exit});

export const bridgeLessons:Lesson[]=[
lessonSchema.parse({
 id:"B2-02-L01",version:1,moduleId:"B2-02",stage:"bridge",title:"Der, die, das: a system that sticks",subtitle:"Genus ist nicht Kasus",minutes:20,
 objectives:["Retrieve a noun as article + noun + plural.","Distinguish a noun's gender from its case.","Use reliable suffixes without overgeneralizing."],prerequisites:[],skills:["gender","noun-packages"],references:["gender","articles","plurals"],vocabulary:["firma","vertrag","angebot","lieferung","rechnung","kunde","ergebnis","termin"],quality,status:"published",
 blocks:[
  {type:"text",title:"Your first day with a new supplier",body:"You read: ‘Die Lieferung kommt morgen. Bitte stimmen Sie den Termin mit der Firma ab.’ Why does Firma appear with der? Its gender has not changed. German uses the same article forms for several different jobs. Separate the noun's dictionary gender from the case required by this sentence."},
  {type:"example",german:"die Firma → mit der Firma",english:"the company → with the company",note:"Firma is feminine in both phrases. Mit requires dative, so feminine die becomes der."},
  {type:"diagram",title:"Two decisions, in the right order",steps:[{label:"Meaning",detail:"Firma = company"},{label:"Gender",detail:"die Firma: feminine"},{label:"Case",detail:"mit requires dative"},{label:"Form",detail:"mit der Firma"}]},
  {type:"table",title:"Learn packages, not isolated nouns",headers:["Noun package","Meaning","Useful phrase"],rows:[["der Vertrag · die Verträge","contract","einen Vertrag unterschreiben"],["die Lieferung · die Lieferungen","delivery","eine Lieferung erhalten"],["das Angebot · die Angebote","offer","ein Angebot prüfen"],["der Termin · die Termine","appointment/deadline","einen Termin vereinbaren"]]},
  {type:"text",title:"Reliable clues and honest limits",body:"True -ung, -heit and -keit formations are feminine: die Rechnung, die Sicherheit, die Möglichkeit. Diminutives with -chen/-lein are neuter: das Mädchen, das Büchlein. A nominalized infinitive is neuter: das Lernen. Final letters alone do not prove a suffix: der Sprung is not an -ung derivation. The common -e → feminine pattern is only a tendency: der Kunde and das Ende are counterexamples."},
  {type:"reading",title:"A small workplace note",body:"Die Firma Nordlicht hat ein Angebot geschickt. Der Preis gilt bis Freitag. Die Lieferung ist für Montag geplant. Bitte prüfen Sie das Angebot und bestätigen Sie den Termin. Der Kunde wartet auf unsere Antwort."},
  {type:"text",title:"A 30-second memory routine",body:"Say the full noun package aloud. Picture a concrete workplace situation. Cover the article and retrieve it. Finally use the noun after a preposition: die Lieferung → mit der Lieferung. Check the form rather than guessing from a color. If you hesitate, keep the item in tomorrow's review."},
 ],
 exercises:[
  choice("B2-02-L01-Q01","What is the dictionary article of Firma?",["der","die","das"],"die","Firma is feminine: die Firma. In mit der Firma, der is the feminine dative form.","gender","GEN"),
  choice("B2-02-L01-Q02","Which explanation of mit der Firma is correct?",["Firma becomes masculine.","Firma stays feminine; mit requires dative.","Every preposition takes der."],"Firma stays feminine; mit requires dative.","Gender is a lexical property. Case changes the article form required by the construction.","gender","CASE"),
  choice("B2-02-L01-Q03","Which noun shows a true feminine -ung derivation?",["der Sprung","die Lieferung","der Schwung"],"die Lieferung","Lieferung is derived from liefern using -ung. Sprung and Schwung only share the final letters.","gender","GEN"),
  short("B2-02-L01-Q04","Complete the noun package: ___ Angebot (write the article).",["das"],"The noun is das Angebot; its plural is die Angebote.","noun-packages","GEN"),
  short("B2-02-L01-Q05","Write the plural of der Vertrag with its article.",["die Verträge"],"Vertrag forms its plural with -e and an umlaut: die Verträge. Do not replace ä with a.","noun-packages","NOUN"),
  choice("B2-02-L01-Q06","In the note, what is planned for Monday?",["The delivery","The end of the offer's price validity","The customer meeting"],"The delivery","Die Lieferung ist für Montag geplant. The price is valid until Friday; no customer meeting is mentioned.","reading-detail","LEX"),
  short("B2-02-L01-Q07","Write the article for Lernen when it means the activity of learning.",["das"],"Infinitives used as nouns are neuter: das Lernen.","gender","GEN",true),
  short("B2-02-L01-Q08","Write the dictionary package for customer in the singular: article + Kunde.",["der Kunde"],"It is der Kunde. The ending -e is not a universal feminine rule.","gender","GEN",true),
 ],reflection:"Which noun did you almost guess incorrectly? Retrieve its whole package before you finish.",
}),
lessonSchema.parse({
 id:"B2-02-L02",version:1,moduleId:"B2-02",stage:"bridge",title:"Cases that do a job",subtitle:"Wer macht was für wen?",minutes:25,
 objectives:["Choose case from a verb or preposition.","Use definite, indefinite and negative articles.","Handle dative plural and weak noun endings."],prerequisites:["B2-02-L01"],skills:["case","noun-endings"],references:["articles","noun-endings","prepositions"],vocabulary:["kunde","kollege","vertrag","angebot","team","mitarbeiter","rechnung","projekt"],quality,status:"published",
 blocks:[
  {type:"text",title:"Follow the relationships",body:"In ‘Die Kollegin schickt dem Kunden den Vertrag’, the colleague is the subject, the customer is the recipient, and the contract is what she sends. These roles help explain nominative, dative and accusative here. Always learn a verb's construction; not every recipient-like meaning mechanically takes dative."},
  {type:"diagram",title:"A sentence with three roles",steps:[{label:"Subject · nominative",detail:"Die Kollegin"},{label:"Verb",detail:"schickt"},{label:"Recipient · dative",detail:"dem Kunden"},{label:"Object · accusative",detail:"den Vertrag"}]},
  {type:"table",title:"Definite articles",headers:["Case","Masculine","Feminine","Neuter","Plural"],rows:[["Nominative","der","die","das","die"],["Accusative","den","die","das","die"],["Dative","dem","der","dem","den"],["Genitive","des","der","des","der"]]},
  {type:"example",german:"Wir haben keinen Vertrag. Wir sprechen mit einem Kunden.",english:"We do not have a contract. We are speaking with a customer.",note:"Keinen marks masculine accusative. Einem marks masculine dative; Kunde also takes -n."},
  {type:"text",title:"The noun sometimes changes too",body:"Dative plurals often add -n: mit den Verträgen. Do not add an extra -n to Kunden or Teams. Weak masculine Kunde becomes Kunden outside nominative singular: den Kunden, dem Kunden, des Kunden. Mixed Name has des Namens. A genitive masculine article does not mean you should always add -s to the noun."},
  {type:"table",title:"Small words, complete phrases",headers:["Phrase","Analysis"],rows:[["mit der Kollegin","mit + dative, feminine"],["für den Kunden","für + accusative; weak noun ending"],["die Prüfung des Angebots","genitive relationship; neuter noun -s"],["mit den Teams","dative plural; existing -s plural stays unchanged"],["keine Angebote","negative indefinite plural; ein has no plural"]]},
 ],exercises:[
  short("B2-02-L02-Q01","Complete: Die Kollegin schickt ___ Kunden den Vertrag. Write the definite article.",["dem"],"Schicken uses a dative recipient: dem Kunden.","case","CASE"),
  short("B2-02-L02-Q02","Complete: Wir prüfen ___ Vertrag. Write the definite article.",["den"],"Prüfen takes an accusative object. Vertrag is masculine: den Vertrag.","case","CASE"),
  choice("B2-02-L02-Q03","Which dative plural is correct?",["mit den Teams","mit den Teamsn","mit die Teams"],"mit den Teams","Mit requires dative. Plurals already ending in -s do not receive another -n.","noun-endings","NOUN"),
  short("B2-02-L02-Q04","Complete: mit den ___ (Vertrag, plural).",["Verträgen"],"Die Verträge becomes den Verträgen in dative plural.","noun-endings","NOUN"),
  short("B2-02-L02-Q05","Complete: die Rückmeldung des ___ (Kunde).",["Kunden"],"Kunde is a weak masculine noun. Its genitive is des Kunden, not des Kundes.","noun-endings","NOUN"),
  choice("B2-02-L02-Q06","Which phrase means no offers?",["keine Angebote","ein Angebote","keinen Angebot"],"keine Angebote","Ein has no plural. Keine is used for negative plural nominative/accusative here.","case","CASE"),
  short("B2-02-L02-Q07","Complete: Wir danken ___ Kollegin. Write the definite article.",["der"],"Danken governs dative: der Kollegin. Learn jemandem danken as a verb package.","case","CASE",true),
  short("B2-02-L02-Q08","Write the full phrase: für + der Kunde.",["für den Kunden"],"Für requires accusative; der becomes den and the weak noun Kunde becomes Kunden.","noun-endings","NOUN",true),
 ],reflection:"Explain separately why the article and noun change in für den Kunden.",
}),
lessonSchema.parse({
 id:"B2-03-L01",version:1,moduleId:"B2-03",stage:"bridge",title:"Adjective endings without guesswork",subtitle:"Ein klarer Plan",minutes:25,
 objectives:["Select an adjective pattern from the determiner.","Apply weak, mixed and strong endings.","Keep adjective and noun endings separate."],prerequisites:["B2-02-L02"],skills:["adjective-endings"],references:["adjectives","articles","noun-endings"],vocabulary:["vertrag","lieferung","konto","ergebnis","service","qualitat","material","plan"],quality,status:"published",
 blocks:[
  {type:"text",title:"Who carries the grammatical signal?",body:"Compare der neue Vertrag, ein neuer Vertrag and neuer Vertrag. A fully marked der-word allows the weak adjective pattern. An ein-word sometimes lacks an ending, so the adjective supplies the missing signal. With no determiner, use the strong pattern. First decide gender, number and case; then choose the pattern."},
  {type:"diagram",title:"An ending in three decisions",steps:[{label:"Gender + case",detail:"Vertrag: masculine nominative"},{label:"Determiner",detail:"ein has no ending here"},{label:"Adjective",detail:"neu + er"},{label:"Phrase",detail:"ein neuer Vertrag"}]},
  {type:"table",title:"Compare the three patterns",headers:["Case/example","Weak","Mixed","Strong"],rows:[["Masculine nominative","der neue Vertrag","ein neuer Vertrag","neuer Vertrag"],["Masculine accusative","den neuen Vertrag","einen neuen Vertrag","neuen Vertrag"],["Neuter nominative","das neue Konto","ein neues Konto","neues Konto"],["Feminine dative","der neuen Lieferung","einer neuen Lieferung","neuer Lieferung"],["Plural dative","den neuen Verträgen","keinen neuen Verträgen","neuen Verträgen"]]},
  {type:"example",german:"Wir arbeiten mit einem erfahrenen Kollegen an einer neuen Lösung.",english:"We are working with an experienced colleague on a new solution.",note:"Mit and arbeiten an use dative here. Both ein-words are inflected, so the adjective ending is -en."},
  {type:"text",title:"Two useful limits",body:"Weak adjectives use -e in singular nominative and feminine/neuter accusative; elsewhere they use -en. In the strong genitive masculine/neuter, the adjective normally also has -en: wegen schlechten Wetters, die Verarbeitung guten Materials. The noun supplies its own genitive ending. Do not write guten Material when Materials is required."},
  {type:"reading",title:"A product description",body:"Unser neuer Scanner erfasst kleine Etiketten zuverlässig. Das robuste Gehäuse schützt die empfindlichen Bauteile. Mit einem zusätzlichen Akku kann das Gerät länger eingesetzt werden. Wir empfehlen regelmäßige Wartung und die Verwendung geeigneten Zubehörs."},
 ],exercises:[
  short("B2-03-L01-Q01","Complete: ein ___ Vertrag (neu, nominative).",["neuer"],"Ein has no nominative masculine ending, so the adjective has -er.","adjective-endings","ADJ"),
  short("B2-03-L01-Q02","Complete: das ___ Konto (neu, nominative).",["neue"],"After das, the weak nominative neuter ending is -e.","adjective-endings","ADJ"),
  short("B2-03-L01-Q03","Complete: mit einer ___ Lieferung (neu).",["neuen"],"Mit requires dative. After einer, the adjective takes -en.","adjective-endings","ADJ"),
  short("B2-03-L01-Q04","Complete: ___ Qualität ist wichtig. (gut, no article).",["Gute"],"Quality is feminine nominative. Strong -e gives gute; at the start of the sentence, capitalize Gute.","adjective-endings","ADJ"),
  choice("B2-03-L01-Q05","Choose the correct genitive phrase.",["die Verarbeitung guten Materials","die Verarbeitung gutes Materials","die Verarbeitung gutem Material"],"die Verarbeitung guten Materials","Strong genitive masculine/neuter adjectives take -en here; the noun Material takes -s.","adjective-endings","ADJ"),
  short("B2-03-L01-Q06","Complete: die ___ Verträge (neu, nominative plural).",["neuen"],"After definite die in the plural, use weak -en: die neuen Verträge.","adjective-endings","ADJ"),
  short("B2-03-L01-Q07","Complete: Wir brauchen ein ___ Angebot. (verbindlich)",["verbindliches"],"Angebot is neuter accusative. Ein is uninflected, so the adjective takes -es.","adjective-endings","ADJ",true),
  short("B2-03-L01-Q08","Complete: mit ___ Ergebnissen (gut, no article).",["guten"],"Strong dative plural uses -en. The noun Ergebnisse also takes dative plural -n.","adjective-endings","ADJ",true),
 ],reflection:"When an adjective ending is wrong, check your earlier gender and case decisions before memorizing another ending.",
}),
lessonSchema.parse({
 id:"B2-01-L01",version:1,moduleId:"B2-01",stage:"bridge",title:"Give every verb its place",subtitle:"Heute schicken wir das Angebot ab",minutes:25,
 objectives:["Keep the finite verb in the second main-clause position.","Build sentence brackets with separable verbs and perfect tense.","Use verb-final subordinate clauses."],prerequisites:[],skills:["word-order"],references:["word-order","connectors"],vocabulary:["angebot","schicken","bestatigen","verschieben","meeting","frist","prufen","antwort"],quality,status:"published",
 blocks:[
  {type:"text",title:"Second position means a unit, not the second word",body:"In ‘Nach dem Meeting schicken wir das Angebot’, the whole phrase Nach dem Meeting occupies position one. Schicken is the finite verb in position two. If a time phrase starts the sentence, the subject normally follows the finite verb. Do not copy English subject–verb order after every opening phrase."},
  {type:"diagram",title:"The sentence bracket",steps:[{label:"First position",detail:"Heute"},{label:"Finite verb",detail:"schicken"},{label:"Middle field",detail:"wir das Angebot"},{label:"Right bracket",detail:"ab"}]},
  {type:"table",title:"One message, three constructions",headers:["Construction","Example"],rows:[["Separable present","Wir schicken das Angebot heute ab."],["Perfect","Wir haben das Angebot heute abgeschickt."],["Modal verb","Wir müssen das Angebot heute abschicken."],["Subordinate clause","…, weil wir das Angebot heute abschicken müssen."]]},
  {type:"example",german:"Weil die Freigabe fehlt, verschieben wir den Termin.",english:"Because approval is missing, we are postponing the appointment.",note:"The whole weil-clause occupies first position; verschieben begins the main clause immediately after it."},
  {type:"text",title:"Negation with a target",body:"Nicht usually comes before the element being contrasted: nicht heute, sondern morgen. In ‘Wir bestätigen den Termin nicht’, the statement is negated. Kein negates an indefinite noun phrase: Wir haben keinen Termin. Word-order memory rules describe defaults; information focus can change the middle field."},
  {type:"reading",title:"A schedule update",body:"Heute prüfen wir die Unterlagen. Weil noch eine Bestätigung fehlt, schicken wir das Angebot erst morgen ab. Den Kunden haben wir bereits informiert. Bitte rufen Sie ihn am Nachmittag an, falls weitere Fragen entstehen."},
 ],exercises:[
  choice("B2-01-L01-Q01","Choose the correct main clause.",["Heute wir prüfen das Angebot.","Heute prüfen wir das Angebot.","Heute das Angebot wir prüfen."],"Heute prüfen wir das Angebot.","Heute occupies first position; prüfen is the finite verb in second position.","word-order","VPOS"),
  short("B2-01-L01-Q02","Complete only the missing verb: weil die Freigabe ___. (fehlen, present)",["fehlt"],"A weil-clause has the finite verb at its end. Die Freigabe is singular: fehlt.","word-order","VPOS"),
  short("B2-01-L01-Q03","Finish the separable verb: Wir rufen den Kunden morgen ___.",["an"],"Anrufen separates in this main clause: rufen … an.","word-order","VPOS"),
  choice("B2-01-L01-Q04","Choose the correct clause after weil.",["weil wir müssen das Angebot prüfen","weil wir das Angebot prüfen müssen","weil müssen wir das Angebot prüfen"],"weil wir das Angebot prüfen müssen","In this subordinate clause, the infinitive prüfen precedes the finite modal müssen at the end.","word-order","VPOS"),
  short("B2-01-L01-Q05","Rewrite with Heute first: Wir haben den Termin bestätigt. Write the complete sentence.",["Heute haben wir den Termin bestätigt."],"The finite auxiliary haben stays in second position; bestätigt closes the bracket.","word-order","VPOS"),
  choice("B2-01-L01-Q06","According to the update, when will the offer be sent?",["Today","Tomorrow","It has already been sent"],"Tomorrow","Erst morgen means not until tomorrow. The customer has already been informed, but the offer has not yet been sent.","reading-detail","LEX"),
  short("B2-01-L01-Q07","Combine using weil: Wir warten. Die Rückmeldung fehlt. Write the complete sentence.",["Wir warten, weil die Rückmeldung fehlt."],"Weil introduces a subordinate clause with fehlt at the end. The comma separates the clauses.","word-order","VPOS",true),
  short("B2-01-L01-Q08","Start with the subordinate clause: Wir warten, weil die Rückmeldung fehlt.",["Weil die Rückmeldung fehlt, warten wir."],"The subordinate clause occupies first position; the main finite verb warten follows it immediately.","word-order","VPOS",true),
 ],reflection:"Read a sentence you wrote recently. Mark its finite verb and, if present, its right bracket.",
}),
lessonSchema.parse({
 id:"B2-06-L01",version:1,moduleId:"B2-06",stage:"bridge",title:"Prepositions with a reason",subtitle:"Im Büro oder ins Büro?",minutes:25,
 objectives:["Distinguish spatial destination from location.","Retrieve fixed verb–preposition packages.","Avoid the blanket rule that time expressions take dative."],prerequisites:["B2-02-L02"],skills:["prepositions"],references:["prepositions","articles"],vocabulary:["buro","besprechung","teilnehmen","warten","bewerben","unternehmen","wochenende","projekt"],quality,status:"published",
 blocks:[
  {type:"text",title:"Movement is not the deciding factor",body:"‘Ich gehe ins Büro’ describes entering the office, a destination. ‘Ich gehe im Büro auf und ab’ describes walking around within a location. Both contain movement, but the first uses accusative and the second dative. Ask about the relationship expressed by the two-way preposition."},
  {type:"diagram",title:"Choose the construction first",steps:[{label:"Spatial destination",detail:"in + accusative → ins Büro"},{label:"Spatial location",detail:"in + dative → im Büro"},{label:"Fixed combination",detail:"teilnehmen an + dative"},{label:"Temporal use",detail:"learn the specific phrase"}]},
  {type:"table",title:"Useful workplace packages",headers:["Package","Example"],rows:[["warten auf + accusative","Wir warten auf die Rückmeldung."],["teilnehmen an + dative","Sie nimmt an der Besprechung teil."],["sich bewerben um + accusative","Er bewirbt sich um die Stelle."],["sich bewerben bei + dative","Sie bewirbt sich bei einem Unternehmen."],["abhängig von + dative","Der Termin ist von der Freigabe abhängig."]]},
  {type:"example",german:"Worauf warten Sie? — Auf die Freigabe. Wir warten darauf.",english:"What are you waiting for? — Approval. We are waiting for it.",note:"For a person, use Auf wen warten Sie? — Auf die Kollegin. Da-/wo-compounds normally refer to things or propositions."},
  {type:"text",title:"Time has its own constructions",body:"Im Mai, am Montag and vor einer Woche use dative. Über das Wochenende and für einen Monat use accusative. Jeden Montag is an accusative time expression without a preposition. A spatial shortcut does not explain every temporal or abstract construction. Learn bis zum Termin as bis + zu, where zu governs dative."},
  {type:"reading",title:"Planning a workshop",body:"Am Montag findet die Besprechung im großen Raum statt. Alle Projektleitungen nehmen daran teil. Die Unterlagen bleiben über das Wochenende im Büro. Bitte warten Sie mit dem Versand auf die Freigabe der Teamleiterin."},
 ],exercises:[
  choice("B2-06-L01-Q01","You enter the office. Choose the phrase.",["Ich gehe im Büro.","Ich gehe ins Büro."],"Ich gehe ins Büro.","Entering the office describes a spatial destination: in + accusative, in das → ins.","prepositions","PREP"),
  choice("B2-06-L01-Q02","You walk around inside the office. Choose the phrase.",["Ich gehe im Büro auf und ab.","Ich gehe ins Büro auf und ab."],"Ich gehe im Büro auf und ab.","The walking happens within a location, so in takes dative despite the movement.","prepositions","PREP"),
  short("B2-06-L01-Q03","Complete: Ich nehme ___ der Besprechung teil. Write the preposition.",["an"],"Teilnehmen an governs dative: an der Besprechung.","prepositions","PREP"),
  short("B2-06-L01-Q04","Complete: Wir warten ___ die Rückmeldung.",["auf"],"Learn warten auf + accusative as a package.","prepositions","PREP"),
  short("B2-06-L01-Q05","Complete: Die Unterlagen bleiben über ___ Wochenende im Büro. Write the definite article.",["das"],"Temporal über takes accusative here: über das Wochenende. Time expressions are not always dative.","prepositions","CASE"),
  choice("B2-06-L01-Q06","Ask which person someone is waiting for.",["Worauf warten Sie?","Auf wen warten Sie?","Wofür warten Sie?"],"Auf wen warten Sie?","For a person use preposition + wen here. Worauf asks about a thing or proposition.","prepositions","PREP"),
  short("B2-06-L01-Q07","Replace auf die Freigabe with a da-compound: Wir warten ___.",["darauf"],"Auf starts with a vowel, so da gains r: darauf.","prepositions","PREP",true),
  short("B2-06-L01-Q08","Complete: Sie bewirbt sich ___ eine Stelle ___ einem Unternehmen. Write the two prepositions separated by a comma.",["um, bei"],"The position uses sich bewerben um + accusative; the employer uses bei + dative.","prepositions","PREP",true),
 ],reflection:"Choose one verb–preposition package and write a sentence that matters in your own work.",
}),
lessonSchema.parse({
 id:"B2-08-L01",version:1,moduleId:"B2-08",stage:"bridge",title:"An email that moves work forward",subtitle:"Klar, höflich und verbindlich",minutes:30,
 objectives:["Write a useful professional email with a clear next action.","Turn blunt internal notes into an appropriate customer message.","Recognize meaningful B2-to-C1 improvements."],prerequisites:["B2-01-L01"],skills:["register","writing","cohesion"],references:["email","connectors","word-order"],vocabulary:["lieferung","verzogerung","ruckmeldung","frist","bestatigen","vereinbaren","verbindlich","bedauern"],quality,status:"published",
 blocks:[
  {type:"reading",title:"The situation",body:"A customer's delivery is two days late. Your team lead writes internally: ‘Lager hat falsch geplant. Lieferung geht Donnerstag raus. Kunde bekommt Versandbestätigung. Bitte prüfen, ob Freitag als Ankunft passt. Keine Zustellung garantieren.’ The customer needs a useful response, not a copy of this internal note."},
  {type:"text",title:"Select the information the recipient needs",body:"Acknowledge the delay, state the confirmed shipping plan, distinguish shipping from arrival, and request the needed response. Do not promise delivery on Friday when only Thursday dispatch is confirmed. Appropriate register includes factual precision, not just polite openings."},
  {type:"diagram",title:"Four moves for a clear reply",steps:[{label:"Acknowledge",detail:"Name the customer's concern"},{label:"Explain",detail:"Give relevant confirmed facts"},{label:"Propose",detail:"State a useful next step"},{label:"Clarify",detail:"Ask for the needed confirmation"}]},
  {type:"table",title:"A B2-to-C1 improvement",headers:["Understandable B2","More precise professional formulation","What improves"],rows:[["Die Lieferung ist spät. Das tut uns leid.","Wir bedauern, dass sich Ihre Lieferung verzögert hat.","Natural collocation and concise acknowledgment"],["Sie bekommen die Ware Freitag.","Der Versand ist für Donnerstag vorgesehen; eine Zustellung am Freitag können wir noch nicht bestätigen.","Separates a plan from a guarantee"],["Schreiben Sie uns bitte.","Bitte teilen Sie uns mit, ob eine voraussichtliche Ankunft am Freitag für Sie infrage kommt.","Makes the requested response specific"]]},
  {type:"example",german:"Sehr geehrte Frau Kaya, wir bedauern die Verzögerung Ihrer Lieferung. Der Versand ist für Donnerstag vorgesehen. Sobald die Sendung übergeben wurde, erhalten Sie eine Versandbestätigung. Eine Zustellung am Freitag können wir noch nicht garantieren. Bitte teilen Sie uns mit, ob dieser voraussichtliche Termin für Sie infrage kommt. Mit freundlichen Grüßen",english:"Dear Ms Kaya, we regret the delay to your delivery. Dispatch is planned for Thursday. Once the shipment has been handed over, you will receive confirmation. We cannot yet guarantee Friday delivery. Please let us know whether this estimated date would work for you. Kind regards."},
  {type:"text",title:"Check before sending",body:"Check the recipient, every requested point, promises and uncertainty, paragraph order, Sie/Ihr forms, finite verbs, commas, and the closing. A simpler accurate sentence is preferable to an impressive but misleading one. C1 writing does not require a long sentence in every paragraph."},
 ],exercises:[
  choice("B2-08-L01-Q01","Which fact is confirmed in the internal note?",["The customer will receive the delivery on Friday.","Dispatch is planned for Thursday.","The customer has accepted the new date."],"Dispatch is planned for Thursday.","The note plans Thursday dispatch and explicitly says not to guarantee arrival.","reading-detail","LEX"),
  choice("B2-08-L01-Q02","Which sentence preserves the uncertainty?",["Die Ware kommt garantiert am Freitag.","Eine Zustellung am Freitag können wir noch nicht bestätigen.","Die Ware ist bereits angekommen."],"Eine Zustellung am Freitag können wir noch nicht bestätigen.","This states the limit of what is known. The alternatives invent a guarantee or a completed delivery.","register","REG"),
  short("B2-08-L01-Q03","Complete the collocation: Wir ___ die Verzögerung. (regret)",["bedauern"],"The professional collocation is eine Verzögerung bedauern.","register","LEX"),
  short("B2-08-L01-Q04","Complete the polite request: Bitte teilen Sie ___ mit, ob der Termin passt.",["uns"],"Jemandem etwas mitteilen uses a dative recipient: uns.","register","CASE"),
  choice("B2-08-L01-Q05","What should a useful final request ask?",["Any response at all","Whether the estimated arrival date would work","Why the warehouse made the error"],"Whether the estimated arrival date would work","The internal instruction asks for the customer's view on Friday. The request should make that next action explicit.","cohesion","REG"),
  short("B2-08-L01-Q06","Complete: Sobald die Sendung übergeben wurde, ___ Sie eine Bestätigung. (erhalten)",["erhalten"],"The preceding subordinate clause occupies first position, so erhalten precedes Sie in the main clause.","word-order","VPOS"),
  choice("B2-08-L01-Q07","Choose the consistent formal address.",["Bitte gib uns deine Rückmeldung, Frau Kaya.","Bitte geben Sie uns Ihre Rückmeldung, Frau Kaya."],"Bitte geben Sie uns Ihre Rückmeldung, Frau Kaya.","Sie and Ihre maintain a consistent formal register.","register","REG",true),
  short("B2-08-L01-Q08","Combine with sobald: Sie erhalten eine Bestätigung. Die Ware wurde versandt. Begin with Sobald.",["Sobald die Ware versandt wurde, erhalten Sie eine Bestätigung."],"The subordinate clause has wurde at its end. The main clause begins with erhalten after the comma.","cohesion","VPOS",true),
  ex({id:"B2-08-L01-Q09",type:"writing",prompt:"Write your own reply to Frau Kaya in 100–150 words. Use the internal note, preserve uncertainty, and request the needed response. Do not copy the model email.",explanation:"A successful reply acknowledges the delay, confirms the dispatch plan, promises shipment confirmation, avoids guaranteeing arrival, and asks about Friday.",hint:"Plan the four communicative moves before writing: acknowledge, explain, propose, clarify.",skill:"writing",family:"customer-delay-reply",transfer:true,exit:true,rubric:["All relevant task points and uncertainty preserved","Appropriate customer register","Clear organization and linking","Accurate grammar and varied appropriate wording"]}),
 ],reflection:"Which change improved the information, rather than merely making the wording more formal?",
})];

export const diagnosticLesson:Lesson=lessonSchema.parse({
 id:"D1",version:1,moduleId:"diagnostic",stage:"bridge",title:"Find your starting point",subtitle:"A short grammar and production check",minutes:20,
 objectives:["Find useful bridge priorities without guessing a whole CEFR level."],prerequisites:[],skills:["gender","case","adjective-endings","word-order","prepositions","verb-forms","connectors"],references:[],vocabulary:[],quality,status:"published",
 blocks:[{type:"text",title:"A check, not an exam",body:"Work without help where you can. You can stop and return later. If you use a hint, that is recorded so the recommendation remains honest."},{type:"text",title:"What this can tell you",body:"These tasks identify likely grammar priorities. A short check does not establish C1, retained mastery, spoken fluency or listening skill."},{type:"text",title:"Your own language matters",body:"After the mixed items, write five sentences about your work. If writing feedback is unavailable, your text is still saved and remains awaiting assessment."}],
 exercises:[
  choice("D1-Q01","Choose the dictionary article of Möglichkeit.",["der","die","das"],"die","True -keit formations are feminine: die Möglichkeit.","gender","GEN"),
  choice("D1-Q02","Choose the correct noun package.",["die Kunde","der Kunde","das Kunde"],"der Kunde","Kunde is masculine; the common -e pattern has exceptions.","gender","GEN"),
  short("D1-Q03","Complete: Wir sprechen mit ___ Kollegin. Use the definite article.",["der"],"Mit governs dative; feminine dative is der.","case","CASE"),
  short("D1-Q04","Complete: Wir unterschreiben ___ Vertrag. Use the definite article.",["den"],"Unterschreiben takes an accusative object. Vertrag is masculine.","case","CASE"),
  short("D1-Q05","Complete: mit den ___ (Vertrag, plural).",["Verträgen"],"Dative plural adds -n to Verträge.","noun-endings","NOUN"),
  short("D1-Q06","Complete: ein ___ Angebot (gut, nominative).",["gutes"],"After uninflected ein with neuter Angebot, the adjective takes -es.","adjective-endings","ADJ"),
  short("D1-Q07","Complete: die ___ Unterlagen (neu, nominative plural).",["neuen"],"The weak plural adjective ending is -en.","adjective-endings","ADJ"),
  choice("D1-Q08","Choose the correct sentence.",["Morgen wir beginnen früher.","Morgen beginnen wir früher."],"Morgen beginnen wir früher.","The finite verb occupies position two after the initial time phrase.","word-order","VPOS"),
  short("D1-Q09","Complete: weil die Besprechung morgen ___. (stattfinden)",["stattfindet"],"In a weil-clause the finite separable verb appears together at the end.","word-order","VPOS"),
  short("D1-Q10","Complete: Sie ___ an der Besprechung teil. (nehmen)",["nimmt"],"The third-person singular is nimmt; teilnehmen separates in a main clause.","verb-forms","VFORM"),
  short("D1-Q11","Complete: Wir haben den Termin ___. (bestätigen)",["bestätigt"],"The inseparable prefix be- does not add ge- in the participle: bestätigt.","verb-forms","VFORM"),
  short("D1-Q12","Complete: Ich warte ___ die Freigabe.",["auf"],"Warten takes auf + accusative in this construction.","prepositions","PREP"),
  choice("D1-Q13","Which temporal expression is correct?",["über dem Wochenende","über das Wochenende"],"über das Wochenende","Temporal über uses accusative here.","prepositions","CASE"),
  choice("D1-Q14","Complete: Die Frist ist kurz. ___ brauchen wir eine schnelle Antwort.",["Trotzdem","Deshalb","Obwohl"],"Deshalb","A short deadline is the reason for needing a quick answer; deshalb signals the consequence.","connectors","CONN"),
  short("D1-Q15","Join using obwohl: Der Preis ist hoch. Wir nehmen das Angebot an. Start with Obwohl.",["Obwohl der Preis hoch ist, nehmen wir das Angebot an."],"Obwohl introduces a concession with verb-final order; nehmen follows the initial subordinate clause.","connectors","CONN"),
  ex({id:"D1-Q16",type:"writing",prompt:"Write five original sentences about your work: a responsibility, a completed task, a plan, a polite request, and a reason using weil. Use no model answer.",hint:"Focus on conveying your own meaning. This is a diagnostic, so imperfect answers are useful.",explanation:"The sentences provide productive evidence across verb forms, word order, register and linking. They need rubric-based evaluation, not a length-only pass.",skill:"writing",family:"diagnostic-work-sentences",transfer:true,exit:true,rubric:["Five requested functions expressed","Accurate verb forms and sentence structure","Appropriate workplace wording"]}),
 ],reflection:"Which part felt uncertain? Confidence is useful context, but your performance drives placement.",
});
