import { lexicalSchema } from "../src/content/types";
const nouns = [
  "problem|Problem|das|Probleme|problem|Pro-BLEM|ein Problem lösen|Das Problem ist noch nicht gelöst.|The problem is not yet solved.",
  "antrag|Antrag|der|Anträge|application; request|AN-trag|einen Antrag einreichen|Der Antrag muss vollständig sein.|The application must be complete.",
  "zustandigkeit|Zuständigkeit|die|Zuständigkeiten|assigned responsibility|ZU-stän-dig-keit|Zuständigkeiten klären|Wir klären die Zuständigkeiten.|We clarify responsibilities.",
  "voraussetzung|Voraussetzung|die|Voraussetzungen|prerequisite; condition|vo-RAUS-set-zung|unter einer Voraussetzung|Die Freigabe ist eine Voraussetzung.|Approval is a prerequisite.",
  "nachweis|Nachweis|der|Nachweise|supporting document; proof|NACH-weis|einen Nachweis vorlegen|Bitte legen Sie den Nachweis vor.|Please provide the supporting document.",
  "beleg|Beleg|der|Belege|receipt; evidence|Be-LEG|einen Beleg einreichen|Für die Erstattung fehlt ein Beleg.|A receipt is missing for reimbursement.",
  "erstattung|Erstattung|die|Erstattungen|reimbursement; refund|Er-STAT-tung|eine Erstattung beantragen|Die Erstattung setzt Belege voraus.|Reimbursement requires receipts.",
  "abweichung|Abweichung|die|Abweichungen|deviation; discrepancy|AB-wei-chung|eine Abweichung begründen|Die Abweichung muss begründet werden.|The deviation must be justified.",
  "einwand|Einwand|der|Einwände|objection|EIN-wand|einen Einwand berücksichtigen|Ihr Einwand ist berechtigt.|Your objection is valid.",
  "einschatzung|Einschätzung|die|Einschätzungen|assessment; impression|EIN-schät-zung|eine Einschätzung abgeben|Das ist eine vorläufige Einschätzung.|This is a preliminary assessment.",
  "auswertung|Auswertung|die|Auswertungen|analysis; evaluation|AUS-wer-tung|Daten zur Auswertung sammeln|Die Auswertung folgt nach dem Test.|Analysis follows the trial.",
  "kennzahl|Kennzahl|die|Kennzahlen|indicator; metric|KENN-zahl|eine Kennzahl festlegen|Wir legen vorab Kennzahlen fest.|We define metrics beforehand.",
  "quote|Quote|die|Quoten|rate; proportion|QUO-te|die Fehlerquote berechnen|Die Quote sank um einen Prozentpunkt.|The rate fell by one percentage point.",
  "stichprobe|Stichprobe|die|Stichproben|sample; spot check|STICH-pro-be|eine Stichprobe prüfen|Die Stichprobe umfasst zwanzig Fälle.|The sample contains twenty cases.",
  "fall|Fall|der|Fälle|case|FALL|einen Fall bearbeiten|Komplexe Fälle gehen an die Fachabteilung.|Complex cases go to the specialist department.",
  "ruckfrage|Rückfrage|die|Rückfragen|follow-up question|RÜCK-fra-ge|Rückfragen vermeiden|Die Anleitung soll Rückfragen vermeiden.|The guide should prevent follow-up questions.",
  "abstimmung|Abstimmung|die|Abstimmungen|coordination; vote by context|AB-stim-mung|die Abstimmung übernehmen|Ich übernehme die Abstimmung mit dem Lager.|I will coordinate with the warehouse.",
  "ubergabe|Übergabe|die|Übergaben|handover|Ü-ber-ga-be|eine Übergabe dokumentieren|Die Übergabe enthält die offenen Punkte.|The handover contains the open points.",
  "vertretung|Vertretung|die|Vertretungen|cover; substitute|Ver-TRE-tung|eine Vertretung organisieren|Für Montag ist eine Vertretung organisiert.|Cover is arranged for Monday.",
  "einweisung|Einweisung|die|Einweisungen|induction; equipment briefing|EIN-wei-sung|eine Einweisung erhalten|Neue Beschäftigte erhalten eine Einweisung.|New employees receive induction.",
  "unterweisung|Unterweisung|die|Unterweisungen|instruction; formal briefing|UN-ter-wei-sung|an einer Unterweisung teilnehmen|Die Unterweisung findet vor Ort statt.|The briefing takes place on site.",
  "zugriff|Zugriff|der|Zugriffe|access|ZU-griff|Zugriff auf etwas haben|Die Vertretung braucht Zugriff auf die Datei.|The substitute needs access to the file.",
  "berechtigung|Berechtigung|die|Berechtigungen|authorization; entitlement|Be-RECH-ti-gung|eine Berechtigung prüfen|Die Berechtigung wird vorher geprüft.|Authorization is checked beforehand.",
  "fassung|Fassung|die|Fassungen|version; wording|FAS-sung|die aktuelle Fassung verwenden|Verwenden Sie die freigegebene Fassung.|Use the approved version.",
  "anlage|Anlage|die|Anlagen|attachment; installation|AN-la-ge|eine Anlage beifügen|Die fehlende Anlage wird nachgereicht.|The missing attachment will follow.",
  "nachlass|Nachlass|der|Nachlässe|discount (price sense)|NACH-lass|einen Nachlass gewähren|Ein höherer Nachlass ist nicht genehmigt.|A larger discount is not approved.",
  "teillieferung|Teillieferung|die|Teillieferungen|partial delivery|TEIL-lie-fe-rung|eine Teillieferung vereinbaren|Die Teillieferung umfasst zehn Geräte.|The partial delivery contains ten devices.",
  "versand|Versand|der|Versände (specialist use; usually singular)|dispatch; shipping|Ver-SAND|den Versand veranlassen|Der Versand erfolgt nach der Freigabe.|Dispatch follows approval.",
  "ursache|Ursache|die|Ursachen|cause|UR-sa-che|eine Ursache untersuchen|Die Ursache ist noch ungeklärt.|The cause remains unclear.",
  "ausfall|Ausfall|der|Ausfälle|failure; outage|AUS-fall|einen Ausfall melden|Der Ausfall dauerte zwanzig Minuten.|The outage lasted twenty minutes.",
  "storung|Störung|die|Störungen|disruption; fault|STÖ-rung|eine Störung beheben|Die Störung wird untersucht.|The fault is being investigated.",
  "umstellung|Umstellung|die|Umstellungen|changeover|UM-stel-lung|eine Umstellung planen|Die Umstellung bindet zunächst Arbeitszeit.|The changeover initially takes staff time.",
  "aufwand|Aufwand|der|Aufwände|effort; expenditure|AUF-wand|den Aufwand abschätzen|Der Aufwand wurde noch nicht gemessen.|The effort has not been measured.",
  "umfang|Umfang|der|Umfänge|scope; extent|UM-fang|den Umfang begrenzen|Wir begrenzen den Umfang des Tests.|We limit the trial's scope.",
  "schlussfolgerung|Schlussfolgerung|die|Schlussfolgerungen|conclusion; inference|SCHLUSS-fol-ge-rung|eine Schlussfolgerung ziehen|Diese Schlussfolgerung geht zu weit.|This conclusion goes too far.",
  "einschrankung|Einschränkung|die|Einschränkungen|restriction; limitation|EIN-schrän-kung|eine Einschränkung benennen|Der Bericht nennt die Einschränkungen.|The report names the limitations.",
  "nachhaltigkeit|Nachhaltigkeit|die|no usual plural|sustainability|NACH-hal-tig-keit|zur Nachhaltigkeit beitragen|Die Maßnahme soll zur Nachhaltigkeit beitragen.|The measure should contribute to sustainability.",
];
const verbs = [
  "anrufen|anrufen|call by phone|AN-ru-fen|rief an · hat angerufen; jemanden anrufen (accusative)|einen Kunden anrufen|Ich rufe den Kunden morgen an.|I will call the customer tomorrow.",
  "bedurfen|bedürfen|require|be-DÜR-fen|bedurfte · hat bedurft; einer Sache bedürfen (genitive)|einer Genehmigung bedürfen|Die Ausnahme bedarf einer Genehmigung.|The exception requires approval.",
  "ableiten|ableiten|derive; infer|AB-lei-ten|leitete ab · hat abgeleitet; etwas aus etwas ableiten|eine Folgerung aus Daten ableiten|Das lässt sich daraus nicht ableiten.|That cannot be inferred from it.",
  "abwaegen|abwägen|weigh up|AB-wä-gen|wog ab · hat abgewogen; etwas gegen etwas abwägen|Vorteile und Nachteile abwägen|Wir wägen die Alternativen sorgfältig ab.|We weigh the alternatives carefully.",
  "obliegen|obliegen|be the responsibility of|ob-LIE-gen|oblag · hat oblegen; etwas obliegt jemandem (dative)|der Leitung obliegen|Die Freigabe obliegt der Leitung.|Approval is management's responsibility.",
  "nachreichen|nachreichen|submit later|NACH-rei-chen|reichte nach · hat nachgereicht; etwas nachreichen|einen Beleg nachreichen|Sie reicht den Beleg morgen nach.|She submits the receipt tomorrow.",
  "veranlassen|veranlassen|arrange; cause|ver-AN-las-sen|veranlasste · hat veranlasst; etwas veranlassen|eine Abholung veranlassen|Wir veranlassen die Abholung.|We arrange collection.",
  "zusagen|zusagen|promise; agree to|ZU-sa-gen|sagte zu · hat zugesagt; jemandem etwas zusagen|einen Termin zusagen|Diesen Termin kann ich noch nicht zusagen.|I cannot promise that date yet.",
];
export const extraVocabulary = [
  ...nouns.map((line) => {
    const [
      id,
      word,
      article,
      plural,
      meaning,
      stress,
      phrase,
      example,
      translation,
    ] = line.split("|");
    return lexicalSchema.parse({
      id,
      word,
      article,
      plural,
      meaning,
      stress,
      phrase,
      example,
      translation,
      type: "noun",
      register: "neutral / professional",
    });
  }),
  ...verbs.map((line) => {
    const [id, word, meaning, stress, forms, phrase, example, translation] =
      line.split("|");
    return lexicalSchema.parse({
      id,
      word,
      meaning,
      stress,
      forms,
      phrase,
      example,
      translation,
      type: "verb",
      register: "neutral / professional",
    });
  }),
];
