import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight,BookOpen,Check,Clock3,RotateCcw,Sparkles,Target,ChartNoAxesCombined } from "lucide-react";
import { requireUser } from "@/auth/server";
import { dashboard } from "@/learning/service";
import TimeBudget from "@/components/time-budget";
export default async function Today(){
 const user=await requireUser();const d=await dashboard(user.id);if(!d.profile.onboardingComplete)redirect("/onboarding");const main=d.tasks.find(t=>t.kind!=="reflection")||d.tasks[0];const date=new Date(`${d.today}T12:00:00Z`).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"});
 return <><div className="page-heading"><div><div className="eyebrow">{date}</div><h1 style={{marginTop:12,marginBottom:0}}>A little closer, {d.profile.name.split(" ")[0]}.</h1><p className="muted">{d.diagnosticDone?"Your next steps, shaped by what you’ve practised.":"Let’s find the right place to begin."}</p></div><TimeBudget profile={d.profile}/></div>
 <div className="metric-grid"><div className="card metric"><div className="stat-label"><BookOpen size={17}/>Lessons completed</div><strong>{d.stats.completed}<span className="muted" style={{fontSize:"1rem"}}> / {d.stats.total}</span></strong><span className="small muted">Published bridge lessons</span></div><div className="card metric"><div className="stat-label"><RotateCcw size={17}/>Reviews due</div><strong>{d.due.length}</strong><span className="small muted">A little retrieval goes a long way</span></div><div className="card metric"><div className="stat-label"><Target size={17}/>Demonstrated objectives</div><strong>{d.stats.demonstrated}</strong><span className="small muted">Based on independent evidence</span></div></div>
 <div className="dashboard-grid"><div className="stack"><section className="card focus-card"><div className="row"><span className="eyebrow">YOUR NEXT BEST STEP</span><Sparkles size={19} color="#c2d9cb"/></div><h2 className="serif">{main?.title||"Explore your learning record"}</h2><p>{main?.reasonText||"Your completed work is saved. Review your progress and choose your next practice."}</p><div className="focus-meta"><span className="row" style={{gap:6}}><Clock3 size={15}/>{main?.estimatedMinutes||5} min</span><span>B2 → C1 bridge</span></div><Link className="button light" href={main?.href||"/progress"}> {d.diagnosticDone?"Continue learning":"Start the short diagnostic"}<ArrowRight size={17}/></Link></section>
 <section className="card"><div className="card-header"><h2>Your session</h2><span className="badge neutral">{d.tasks.reduce((sum,t)=>sum+t.estimatedMinutes,0)} min planned</span></div>{d.tasks.map((task,i)=><Link className="activity" style={{textDecoration:"none"}} key={task.activityId} href={task.href}><span className="activity-icon">{task.kind==="review"?<RotateCcw size={20}/>:task.kind==="reflection"?<Check size={20}/>:<BookOpen size={20}/>}</span><div className="grow"><h3>{i+1}. {task.title}</h3><p className="small muted">{task.reasonText}</p></div><span className="small muted" style={{whiteSpace:"nowrap"}}>{task.estimatedMinutes} min</span></Link>)}</section>
 <section className="card"><div className="card-header"><h2>Make it your own</h2><Link href="/practice" className="inline-link">All practice →</Link></div><div className="grid-two"><Link href="/practice/articles" className="row"><div><h3>Article drill</h3><p className="small muted" style={{margin:0}}>Gender, case, then the whole phrase.</p></div><ArrowRight size={18}/></Link><Link href="/errors" className="row"><div><h3>Practise my mistakes</h3><p className="small muted" style={{margin:0}}>Turn a correction into a useful habit.</p></div><ArrowRight size={18}/></Link></div></section></div>
 <aside className="stack"><section className="card"><div className="card-header"><h2>Your route</h2><span className="badge">Bridge</span></div><div className="journey">{[{title:"A comfortable C1 starting point",text:"B2 foundations, where you need them"},{title:"German for professional life",text:"18 C1 modules"},{title:"DTB C1 preparation",text:"Format, practice and mock exams"},{title:"Toward C2",text:"Nuance, precision and flexibility"}].map((s,i)=><div className={`journey-item ${i===0?"current":""}`} key={s.title}><span className="journey-dot">{i+1}</span><div><h3>{s.title}</h3><p>{s.text}</p></div></div>)}</div><Link href="/course" className="inline-link" style={{display:"block",marginTop:22}}>View your course map →</Link></section>
 <section className="card"><span className="eyebrow">A SMALL DISTINCTION</span><h2 style={{marginTop:12}}>Gender stays. Case changes.</h2><div className="article-demo"><div className="article-tile"><b>der</b><span>Vertrag</span></div><div className="article-tile fem"><b>die</b><span>Firma</span></div><div className="article-tile neut"><b>das</b><span>Angebot</span></div></div><p className="small muted"><span lang="de">Die Firma → mit der Firma.</span> Still feminine. The article changes because <i>mit</i> takes dative.</p><Link href="/reference/gender" className="inline-link">Open the article toolkit →</Link></section>
 <Link href="/progress" className="card row" style={{textDecoration:"none"}}><ChartNoAxesCombined size={24}/><div className="grow"><h3 style={{margin:0}}>Your evidence, clearly</h3><p className="small muted" style={{margin:0}}>{d.stats.attempts} saved attempts · {d.stats.retained} retained objectives</p></div><ArrowRight size={17}/></Link></aside></div></>;
}
